### ISSUE TITLE
bug: KeyError: 'lastlogoff'

### ISSUE THREAD

**Issue by SlightDust** [SlightDust/steam_HoshinoBot#2]
```python
[2024-04-30 01:06:00,287 steam] ERROR: <class 'KeyError'> occured when doing scheduled job check_steam_status.
[2024-04-30 01:06:00,288 steam] ERROR: 'lastlogoff'
Traceback (most recent call last):
  File "/root/qqbot/HoshinoBot/hoshino/service.py", line 350, in wrapper
    ret = await func()
  File "/root/qqbot/HoshinoBot/hoshino/modules/steam/steam.py", line 299, in check_steam_status
    await update_game_status()
  File "/root/qqbot/HoshinoBot/hoshino/modules/steam/steam.py", line 267, in update_game_status
    "lastlogoff": player["lastlogoff"],
KeyError: 'lastlogoff'
```

拿api tester试了一下，非api key持有者的好友，接口好像不会返回lastlogoff这个参数。姑且开个issue记一下。

**Comment by SlightDust** [comment]
参考隔壁[nonebot-plugin-steam-info](https://github.com/zhaomaoniu/nonebot-plugin-steam-info)搞一下
![image](https://github.com/SlightDust/steam_HoshinoBot/assets/53001305/ad84be32-8e4e-4110-b29a-cdec8cc3fcd1)
