### ISSUE TITLE
有些(?)游戏的appdetails总是取不到

### ISSUE THREAD

**Issue by SlightDust** [SlightDust/steam_HoshinoBot#8]
经常报获取游戏名失败，打了一下日志，发现查GTA5的appdetails总是有问题，手动访问一下也经常是空的，不知道什么情况，先记在这。
目前只发现271590有问题
```python
[2024-07-18 22:20:01,329 steam] ERROR: ==============获取游戏名失败: 以下是traceback==============
[2024-07-18 22:20:01,329 steam] ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/qqbot/HoshinoBot/hoshino/modules/steam_HoshinoBot/steam.py", line 315, in get_localized_game_name
    data = await resp.json()
  File "/root/qqbot/HoshinoBot/hoshino/aiorequests.py", line 57, in json
    return await run_sync_func(self.raw_response.json, **kwargs)
  File "/root/qqbot/HoshinoBot/hoshino/aiorequests.py", line 10, in run_sync_func
    return await asyncio.get_event_loop().run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0

[2024-07-18 22:20:01,330 steam] ERROR: =================end traceback=================
[2024-07-18 22:20:01,330 steam] ERROR: url: https://store.steampowered.com/api/appdetails?appids=271590&l=schinese
[2024-07-18 22:20:01,330 steam] ERROR: =================end debug=================

```

**Comment by GaryDu0123** [comment]
我现在访问浏览器那个url是不带language的查询字符串是有英文的结果, 带上`l=schinese`之后就是空白
